### ISSUE TITLE
No published code of conduct

### ISSUE THREAD

**Issue by ticky** [Code-and-Coffee-YVR/Code-and-Coffee-YVR.github.io#2]
I haven’t been able to find the code of conduct your meetup descriptions refer to anywhere. It should probably be prominent on the website and linked to in meetup descriptions!

**Comment by keywordnew** [comment]
Hi @ticky! We're really sorry about that, it really should be way more prominent 😞 

We're working on it! The team is leaning towards borrowing the Code of Conduct used by CascadiaFest, a super inclusive conference run in the Pacific Northwest for the past couple of years.

Check it out here (just for now!)
https://github.com/cascadiajs/2016.cascadiajs.com/blob/master/code-of-conduct.md

Thanks for letting us know, we're on it 💯

**Comment by ticky** [comment]
Looks pretty solid! Thanks for clarifying - might be worth linking to in the event descriptions until it makes it onto your website? :smile:

**Comment by keywordnew** [comment]
That's a great stopgap solution! 😊 We're talking about it, will post developments right here!

**Comment by keywordnew** [comment]
Our [Code of Conduct](https://www.meetup.com/Code-Coffee-Vancouver/pages/19153519/Code_of_Conduct/) is now linked from the event page and from the about us page!

Thanks for making sure we knew to fix this! 💪✨

**Comment by ticky** [comment]
Excellent! 😁

**Comment by keywordnew** [comment]
Closing this issue for now. Thanks for your contribution @ticky! 🙌🏽
